# Generated by Django 3.2.20 on 2023-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=122)),
                ('phone2', models.CharField(max_length=122)),
                ('email2', models.CharField(max_length=122)),
            ],
        ),
    ]
